### ISSUE TITLE
Tempest stops working after upgrade to 2021.4.0

### ISSUE THREAD

**Issue by christianlappin** [briis/smartweatherudp#26]
Getting the below error in the HA log. Any ideas?

Logger: homeassistant.components.sensor
Source: custom_components/smartweatherudp/sensor.py:67
Integration: Sensor (documentation, issues)
First occurred: 10:22:08 AM (1 occurrences)
Last logged: 10:22:08 AM

Error while setting up smartweatherudp platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/smartweatherudp/sensor.py", line 67, in setup_platform
    from pysmartweatherudp import SWReceiver
ImportError: cannot import name 'SWReceiver' from 'pysmartweatherudp' (/usr/local/lib/python3.8/site-packages/pysmartweatherudp/__init__.py)

**Comment by natekspencer** [comment]
If this is still an issue after upgrading to v2021.12.0, please open a new issue.
